version: '2'
services:
  rasa-flask:
    image: rasa-chatbot:latest
    build:
      context:
      dockerfile: Dockerfile
    container_name: rasa-chat-app
    volumes:
      - .:/rasa_app
    ports:
      - 5000:5000
    command: python app.py
  rasa-server:
    image: rasa/rasa:2.1.1-full
    container_name: rasa-chatbot-server
    volumes:
      - .:/app
    ports:
      - 5005:5005
    command: run -m modles --enable-api --cors "*"